# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-16 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0002_auto_20160716_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cfp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfps', to='conferences.Conference')),
            ],
            options={
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('twitter', models.CharField(max_length=20)),
                ('github', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced'), ('all', 'All')], max_length=10)),
                ('note', models.TextField()),
                ('cfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='cfp.Cfp')),
            ],
        ),
    ]
