# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-16 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='difficulty',
            field=models.CharField(choices=[('all', 'All'), ('beginner', 'Beginner'), ('advanced', 'Advanced')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='github',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='twitter',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
