# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-17 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0002_auto_20160716_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfp',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
