# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-17 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0003_cfp_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfp',
            name='template_about',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
