# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-26 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='published',
        ),
        migrations.AddField(
            model_name='talk',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], default='beginner', help_text='Does you audience require high level of Python knowledgeor is it suitable for everyone?', max_length=10),
        ),
        migrations.AddField(
            model_name='talk',
            name='language',
            field=models.CharField(choices=[('en', 'English (preferred)'), ('cs', 'Czechoslovak')], default='en', max_length=2),
        ),
    ]
