# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-26 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_auto_20160926_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='email',
            field=models.EmailField(default='', help_text="We'll keep it secret, for internal use only.", max_length=254),
            preserve_default=False,
        ),
    ]
