# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-27 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0005_auto_20160926_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='talk',
        ),
        migrations.AddField(
            model_name='speaker',
            name='talks',
            field=models.ManyToManyField(to='speakers.Talk'),
        ),
    ]
