# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-10-05 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0006_auto_20160927_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('workshop', 'Workshop'), ('sprint', 'Sprint')], default='sprint', help_text="At a workshop, you should present hands-on excercises for participants to learn from. You'll get a room and a slot in the agenda, and participants will need to register.\n At a sprint, participants help an open-source project -- usually by cloning the repo and trying to fix beginner-level issues, while you'll provide one-to-one mentorship. If several experienced developers are around, sprints are also a good place for serious design discussions. Sprinters only need a table to sit around, reliable wifi, and dedication to do great things!", max_length=10)),
                ('title', models.CharField(help_text='Public title. What topic/project is it all about?', max_length=200, verbose_name='Workshop/sprint title')),
                ('abstract', models.TextField(help_text='Full description of your workshop or sprint. Please also describe requirements: libraries and Python version to be installed, required experience with topics/libraries, etc.')),
                ('language', models.CharField(choices=[('en', 'English (preferred)'), ('cs', 'Czech/Slovak')], default='en', max_length=2)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], default='beginner', help_text='Does you audience require high level of specialized knowledge (of Python, a library, etc.), or is it suitable for everyone?', max_length=10)),
                ('length', models.CharField(blank=True, choices=[('1h', '1 hour'), ('2h', '2 hours'), ('2h', '3 hours'), ('1d', 'Full day (most sprints go here!)'), ('xx', 'Something else! (Please leave a note in the abstract!)')], help_text='How much time does your workshop take? Sprints usually take the whole day, but workshops are organized in smaller blocks. You can also have a full-day workshop with lunch break, but keep in mind that the length could discourage attendees!', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='speaker',
            name='workshops',
            field=models.ManyToManyField(to='speakers.Workshop'),
        ),
    ]
