# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-10-02 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0006_auto_20160927_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('room', models.CharField(max_length=5)),
                ('talk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='speakers.Talk')),
            ],
        ),
    ]
