# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-10-10 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0008_auto_20161006_0929'),
        ('speakers', '0007_slot'),
    ]

    operations = [
    ]
