# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-10-10 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0009_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.CharField(choices=[('foyer', 'Foyer'), ('d105', 'D105'), ('d0206', 'D0206'), ('d0207', 'D0207')], max_length=5),
        ),
        migrations.AlterField(
            model_name='slot',
            name='talk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speakers.Talk'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='talks',
            field=models.ManyToManyField(blank=True, related_name='speakers', to='speakers.Talk'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='workshops',
            field=models.ManyToManyField(blank=True, related_name='workshops', to='speakers.Workshop'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='abstract',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='talk',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], default='beginner', max_length=10),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='abstract',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], default='beginner', max_length=10),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='length',
            field=models.CharField(blank=True, choices=[('1h', '1 hour'), ('2h', '2 hours'), ('2h', '3 hours'), ('1d', 'Full day (most sprints go here!)'), ('xx', 'Something else! (Please leave a note in the abstract!)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('sprint', 'Sprint')], default='sprint', max_length=10),
        ),
    ]
