# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('speakers', '0010_auto_20161010_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='slot',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.CharField(choices=[('foyer', 'Foyer'), ('d105', 'D105'), ('d0206', 'D0206'), ('d0207', 'D0207'), ('a112', 'A112'), ('a113', 'A113')], max_length=5),
        ),
    ]
