# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 09:10
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def migrate_talks(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Slot = apps.get_model("speakers", "Slot")

    # `get_or_create` because of http://stackoverflow.com/q/31539690/325365
    TalkType, created = ContentType.objects.get_or_create(app_label="speakers", model="talk")

    Slot.objects.exclude(talk=None).update(
        object_id=F('talk_id'),
        content_type=TalkType
    )


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('speakers', '0011_auto_20161011_1110'),
    ]

    operations = [
        migrations.RunPython(migrate_talks)
    ]
