# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0012_auto_20161011_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='talk',
        ),
    ]
