# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0013_remove_slot_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='talks',
            field=models.ManyToManyField(blank=True, related_name='talks', to='speakers.Talk'),
        ),
    ]
