# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0014_auto_20161011_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='keynote',
            field=models.BooleanField(default=False),
        ),
    ]
