# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-23 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
