# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-23 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_organizer_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='This is private', max_length=254),
        ),
    ]
