# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-05 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], default='bronze', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.FileField(upload_to='sponsors/pyconcz_2016/')),
                ('description', models.TextField()),
                ('link_url', models.URLField()),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
    ]
