# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
