# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-08 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_sponsor_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('diversity', 'Diversity'), ('media', 'Media')], default='bronze', max_length=20),
        ),
    ]
