# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-25 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('twitter', models.CharField(blank=True, max_length=20)),
                ('github', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('difficulty', models.CharField(choices=[('all', 'All'), ('beginner', 'Beginner'), ('advanced', 'Advanced')], default='all', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('twitter', models.CharField(blank=True, max_length=20)),
                ('github', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('all', 'All'), ('beginner', 'Beginner'), ('advanced', 'Advanced')], default='all', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
