# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-01 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('proposals', '0002_auto_20160801_1020'), ('proposals', '0003_auto_20160801_1020'), ('proposals', '0004_auto_20160801_1021')]

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='github',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='talk',
            name='twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='talk',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='github',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
