# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-09 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20160801_1020_squashed_0004_auto_20160801_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='description',
        ),
        migrations.AddField(
            model_name='talk',
            name='photo',
            field=models.ImageField(default='', help_text='Photo of yourself which we can publish on our website', upload_to='proposals/pyconcz2016/talks/', verbose_name='Your picture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='abstract',
            field=models.TextField(default='', help_text='Full description of your workshop or sprint. Please also describe requirements like installed libraries, Python version, etc.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='length',
            field=models.CharField(blank=True, choices=[('1h', '1 hour'), ('2h', '2 hours'), ('2h', '3 hours'), ('xh', 'Moar!')], help_text='How much time does your workshop take? Sprints usually take whole day, but workshops are organized in smaller blocks. You can also have a full-day workshop with lunch break, if you want to!', max_length=2),
        ),
        migrations.AddField(
            model_name='workshop',
            name='photo',
            field=models.ImageField(default='', help_text='Photo of yourself which we can publish on our website', upload_to='proposals/pyconcz2016/talks/', verbose_name='Your picture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='type',
            field=models.CharField(choices=[('sprint', 'Sprint'), ('workshop', 'Workshop')], default='sprint', help_text='Workshops requires a room, slot in agenda and mandatory registration of participants. Sprints requires only table to sit around, reliable wifi and dedication to do great things!', max_length=10),
        ),
        migrations.AlterField(
            model_name='talk',
            name='abstract',
            field=models.TextField(help_text='Full description of your talk. How would you describe yourtalk to the audience?'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='bio',
            field=models.TextField(help_text='Tell us a bit about yourself! Who you are, where are you from, what are your experiences with Python. Be wild, be creative!'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], default='beginner', help_text='Does you audience require high level of Python knowledgeor is it suitable for everyone?', max_length=10),
        ),
        migrations.AlterField(
            model_name='talk',
            name='email',
            field=models.EmailField(help_text="We'll keep it secret, for internal use only.", max_length=254),
        ),
        migrations.AlterField(
            model_name='talk',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Your name'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='github',
            field=models.CharField(blank=True, max_length=255, verbose_name='GitHub username (optional)'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(help_text='This is going to be public on all posters! Make up some catchy title which attracts audience.', max_length=200, verbose_name='Talk title'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, verbose_name='Twitter handle (optional)'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='bio',
            field=models.TextField(help_text='Tell us a bit about yourself! Who you are, where are you from, what are your experiences with Python. Be wild, be creative!'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], default='beginner', help_text='Does you audience require high level of Python knowledge or is it suitable for everyone?', max_length=10),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='email',
            field=models.EmailField(help_text="We'll keep it secret, for internal use only.", max_length=254),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Your name'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='github',
            field=models.CharField(blank=True, max_length=255, verbose_name='GitHub username (optional)'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(help_text='Public title. What topic/project is it all about?', max_length=200, verbose_name='Workshop/sprint title'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, verbose_name='Twitter handle (optional)'),
        ),
    ]
