# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-11 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_auto_20160809_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='abstract',
            field=models.TextField(help_text='Full description of your workshop or sprint. Please also describe requirements: libraries and Python version to be installed, required experience with topics/libraries, etc.'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], default='beginner', help_text='Does you audience require high level of specialized knowledge (of Python, a library, etc.), or is it suitable for everyone?', max_length=10),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='length',
            field=models.CharField(blank=True, choices=[('1h', '1 hour'), ('2h', '2 hours'), ('2h', '3 hours'), ('1d', 'Full day (most sprints go here!)'), ('xx', 'Something else! (Please leave a note in the abstract!)')], help_text='How much time does your workshop take? Sprints usually take the whole day, but workshops are organized in smaller blocks. You can also have a full-day workshop with lunch break, but keep in mind that the length could discourage attendees!', max_length=2),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='type',
            field=models.CharField(choices=[('sprint', 'Sprint'), ('workshop', 'Workshop')], default='sprint', help_text="At a workshop, you should present hands-on excercises for participants to learn from. You'll get a room and a slot in the agenda, and participants will need to register.\n At a sprint, participants help an open-source project -- usually by cloning the repo and trying to fix beginner-level issues, while you'll provide one-to-one mentorship. If several experienced developers are around, sprints are also a good place for serious design discussions. Sprinters only need a table to sit around, reliable wifi, and dedication to do great things!", max_length=10),
        ),
    ]
