# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-12 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_auto_20160811_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='github',
            field=models.CharField(blank=True, help_text='Optional', max_length=255, verbose_name='GitHub username'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='twitter',
            field=models.CharField(blank=True, help_text='Optional', max_length=255, verbose_name='Twitter handle'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='github',
            field=models.CharField(blank=True, help_text='Optional', max_length=255, verbose_name='GitHub username'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='twitter',
            field=models.CharField(blank=True, help_text='Optional', max_length=255, verbose_name='Twitter handle'),
        ),
    ]
