# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-12 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_auto_20160812_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='language',
            field=models.CharField(choices=[('en', 'English (preferred)'), ('cs', 'Czech/Slovak')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='workshop',
            name='language',
            field=models.CharField(choices=[('en', 'English (preferred)'), ('cs', 'Czech/Slovak')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('sprint', 'Sprint')], default='sprint', help_text="At a workshop, you should present hands-on excercises for participants to learn from. You'll get a room and a slot in the agenda, and participants will need to register.\n At a sprint, participants help an open-source project -- usually by cloning the repo and trying to fix beginner-level issues, while you'll provide one-to-one mentorship. If several experienced developers are around, sprints are also a good place for serious design discussions. Sprinters only need a table to sit around, reliable wifi, and dedication to do great things!", max_length=10),
        ),
    ]
