# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-12 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_auto_20160812_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='language',
            field=models.CharField(choices=[('en', 'English (preferred)'), ('cs', 'Czechoslovak')], default='en', max_length=2),
        ),
    ]
