# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-08 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_auto_20160812_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('full_name', models.CharField(max_length=200, verbose_name='Your name')),
                ('email', models.EmailField(help_text="We'll keep it secret, for internal use only.", max_length=254)),
                ('bio', models.TextField(help_text='Tell us a bit about yourself! Who you are, where are you from, what are your experiences with Python. Also include how are you involved in Python community and how do you contribute or do you plan to contribute to community.')),
                ('amount', models.TextField(help_text='How much money would you like to get (please specify currency).')),
                ('purpose', models.TextField(help_text='How would you like to use granted money?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
