# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-08 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_financialaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaid',
            name='amount',
            field=models.CharField(help_text='How much money would you like to get (please specify currency).', max_length=255),
        ),
    ]
