# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-08 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_auto_20160908_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaid',
            name='bio',
            field=models.TextField(help_text='Tell us a bit about yourself! Who you are, where you are from, and what your experiences with Python are. Also include how you are involved in Python community and how you contribute or plan to contribute to the community.'),
        ),
    ]
