# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-18 23:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_auto_20160919_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='note',
            field=models.CharField(blank=True, default='', help_text='Only you can see this', max_length=255),
        ),
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.PositiveSmallIntegerField(help_text='4 = Must have!, 3 = Interesting talk, 2 = Meh, 1 = Definitely not!', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
