# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-16 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['date_start']},
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='date_ended',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='date_started',
            new_name='date_start',
        ),
    ]
